INSERT INTO task (id,
                  content,
                  date_added,
                  date_completed,
                  description,
                  has_more_notes,
                  in_history,
                  is_deleted,
                  parent_id,
                  priority,
                  project_id,
                  section_id,
                  user_id)
VALUES ($id,
        '$content',
        '$date_added',
        '$date_completed',
        '$description',
        $has_more_notes,
        $in_history,
        $is_deleted,
        $parent_id,
        $priority,
        $project_id,
        $section_id,
        $user_id)
;
